language: php

php:
  - 7.1
  - 7.2

before_install:
  - composer install --dev --ignore-platform-reqs

script:
  - mkdir -p build/logs
  - php vendor/bin/phpcs --standard=ruleset.xml src
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
