language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_install:
  - composer install

script:
  - mkdir -p build/logs
  - php vendor/bin/phpcs --standard=ruleset.xml src tests
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/php-coveralls -v
